adminUser: admin
adminPassword: admin123

service:
  type: LoadBalancer

persistence:
  enabled: true
  size: 10Gi
  storageClassName: gp2

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local
        access: proxy
        isDefault: true
