mode: daemonset

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true

  hostMetrics:
    enabled: true

  kubernetesAttributes:
    enabled: true

config:
  exporters:
    otlp:
      endpoint: "http://prometheus-server.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true

  service:
    pipelines:
      metrics:
        receivers: [ prometheus, hostmetrics ]
        processors: [ batch, memory_limiter, k8sattributes ]
        exporters: [ otlp ]

      logs:
        receivers: [ filelog ]
        processors: [ batch, memory_limiter, k8sattributes ]
        exporters: [ otlp ]

  receivers:
    prometheus:
      config:
        scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
          - targets: [ '${MY_POD_IP}:8888' ]
    filelog:
      include:
      - /var/log/pods/*/*/*.log
      start_at: beginning
    hostmetrics:
      collection_interval: 10s
      scrapers:
        cpu: {}
        load: {}
        memory: {}
        disk: {}
        filesystem: {}
        network: {}
