name: max-pods-eks

on:
  workflow_dispatch:

jobs:
  enable-prefix-delegation:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your region

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name dev-eks-cluster  # Replace with your cluster name

      - name: Enable prefix delegation
        run: |
          echo "Setting ENABLE_PREFIX_DELEGATION to true..."
          kubectl set env daemonset aws-node -n kube-system ENABLE_PREFIX_DELEGATION=true

          echo "Setting WARM_PREFIX_TARGET to 1..."
          kubectl set env daemonset aws-node -n kube-system WARM_PREFIX_TARGET=1

          echo "Restarting aws-node DaemonSet..."
          kubectl rollout restart daemonset aws-node -n kube-system

      - name: Confirm aws-node logs
        run: |
          echo "Waiting for aws-node pods to restart..."
          sleep 20
          kubectl get pods -n kube-system -l k8s-app=aws-node
